import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../globals.css";

import DashboardLayout from "@/components/ComponentsLayout";
import TanStackProvider from "@/components/TanStackProvider";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TanStackProvider>
      <div
        className={`${roboto.variable} ${roboto.variable} antialiased flex w-full`}>
        <DashboardLayout>{children}</DashboardLayout>
      </div>
    </TanStackProvider>
  );
}
