import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

import TanStackProvider from "@/components/TanStackProvider";
import { ToastContainer } from "react-toastify";
import { LoadingBar } from "@/components/Progress";
import { Suspense } from "react";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${roboto.variable} antialiased flex`}>
        <Suspense fallback={<div>Loading...</div>}>
          <TanStackProvider>{children}</TanStackProvider>
          <ToastContainer />
          <LoadingBar />
        </Suspense>
      </body>
    </html>
  );
}
